apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 3 # desired number of pod instances
  selector: # determines what pods the RC is operating on. This can be omitted.
            # K8 then will take label selector from labels in Pod template
    app: kubia
  template: # template for creating new pods
    metadata:
      labels: # must match RC selector! Otherwise RC will spin Pods indefinitely
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 8080