apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy # app image
    name: kubia-unhealthy
    livenessProbe:
      httpGet: # spec of HTTP request
        path: /
        port: 8080
      initialDelaySeconds: 15 # K8 will wait 15 seconds before executing the first probe to account for app's startup