apiVersion: batch/v1
kind: Job
metadata:
  name: cron-batch-job
spec:
  schedule: "0,15,30,45 * * * *" # every 15 minutes
  startingDeadlineSeconds: 15 # At the latest, the pod must start running at 15 seconds past the scheduled time.
  jobTemplate:
    metadata:
      labels: # pod selector will be crated based on this labels
        app: periodic-batch-job
    spec:
      restartPolicy: OnFailure # OnFailure or Never. Only restart if error occurs, otherwise - complete.
      containters:
        - name: main
          image: luksa/batch-job


